# This script was automatically generated by CraftingTable.py
# You can edit it to add your own features.
# Visit Modrinth or GitHub for documentation and examples.

import craftingtable as mc

async def on_player_join(player):
    mc.cmd(f"title {player} actionbar Welcome to the server, {player}!")
    mc.cmd(f"give {player} minecraft:apple 5")

async def on_player_leave(player):
    mc.log(f"Player left: {player}")

async def on_chat(message, type, player):
    if message == "hello":
        mc.cmd(f"say Hello, {player}!")

async def on_item_use(world, item_id, count, player, hand, nbt=None):
    if item_id == "stick":
        mc.cmd(f"say {player} used a non-magical stick...")
        mc.cmd(f"effect give {player} minecraft:slowness 5 1")